# Generated by Django 2.2.5 on 2021-01-26 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SigfoxData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('temp', models.FloatField()),
                ('humid', models.FloatField()),
                ('light', models.IntegerField()),
                ('sound', models.FloatField()),
                ('butt', models.FloatField()),
            ],
        ),
    ]
