# Generated by Django 2.2.5 on 2021-01-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_sigfoxdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='sigfoxdata',
            name='device',
            field=models.CharField(default='test', max_length=20),
        ),
    ]
